from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import pytest
from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[1]
XML_CONVERTER = ROOT / "convert_wmdr10_xml_to_wmdr10_json.py"
JSON_CONVERTER = ROOT / "convert_wmdr10_json_to_wmdr2_json.py"
XML_SOURCE_DIR = ROOT / "resources" / "wmdr10_xml_examples"
SCHEMA_FILE = ROOT / "schemas" / "wmdr2-record-feature.schema.json"

# Records listed here are generated by the end-to-end conversion but are not
# advertised as schema-valid WMDR2 examples.  The source XML contains contact
# phone numbers without enough information to normalize them to the strict OGC
# Contact / E.164 pattern.  Keep these records visible here instead of
# weakening the OGC Contact schema.
KNOWN_NONVALIDATING_E2E_OUTPUTS: dict[str, str] = {
    "20200304_0-20000-0-06494.json": "source has an observingConfiguration without a recorded validity time",
    "20220511_0-404-0-63707.json": "source contact phone is local-only, e.g. 0722782074",
    "20250314_0-404-800-4AA01.json": "source contact phone is local-only, e.g. 0722442639",
    "20250504_0-20008-0-NRB.json": "source contact phone is not E.164, e.g. 254723521586 without +",
    "20251218_0-20000-0-45004.json": "source has an observingConfiguration without a recorded validity time",
    "20260318_0-20008-0-DAV.json": "source has an observingConfiguration without a recorded validity time",
}


def _load_module(path: Path, name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        pytest.fail(f"Cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="session")
def e2e_outputs(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    if not XML_CONVERTER.exists() or not XML_SOURCE_DIR.exists():
        pytest.skip("XML converter or XML example resources are not present in this checkout")
    work = tmp_path_factory.mktemp("xml_to_wmdr2")
    wmdr10 = work / "wmdr10_json"
    wmdr2 = work / "wmdr2_json"

    xml_module = _load_module(XML_CONVERTER, "_wmdr2_e2e_xml_converter")
    json_module = _load_module(JSON_CONVERTER, "_wmdr2_e2e_json_converter")
    xml_module.main(["--config", str(ROOT / "config.yaml"), "--source", str(XML_SOURCE_DIR), "--target", str(wmdr10)])
    json_module.main(["--config", str(ROOT / "config.yaml"), "--source", str(wmdr10), "--target", str(wmdr2)])
    return {"wmdr10": wmdr10, "wmdr2": wmdr2}


def test_end_to_end_conversion_writes_one_wmdr2_record_per_xml(e2e_outputs: dict[str, Path]) -> None:
    xml_files = sorted(XML_SOURCE_DIR.glob("*.xml"))
    assert xml_files
    for xml_path in xml_files:
        assert (e2e_outputs["wmdr2"] / f"{xml_path.stem}.json").exists()


def test_end_to_end_wmdr2_records_validate_against_schema(e2e_outputs: dict[str, Path]) -> None:
    schema = json.loads(SCHEMA_FILE.read_text(encoding="utf-8"))
    validator = Draft202012Validator(schema)
    outputs = sorted(e2e_outputs["wmdr2"].glob("*.json"))
    assert outputs
    failures: list[str] = []
    validated: list[str] = []
    unexpectedly_valid: list[str] = []
    for output in outputs:
        payload = json.loads(output.read_text(encoding="utf-8"))
        errors = sorted(validator.iter_errors(payload), key=lambda err: list(err.path))
        if errors:
            if output.name in KNOWN_NONVALIDATING_E2E_OUTPUTS:
                continue
            first = errors[0]
            path = "/".join(str(part) for part in first.path) or "<root>"
            failures.append(f"{output.name}: {path}: {first.message}")
        elif output.name in KNOWN_NONVALIDATING_E2E_OUTPUTS:
            unexpectedly_valid.append(output.name)
        else:
            validated.append(output.name)

    # Do not require at least one schema-valid E2E fixture here. Some
    # resource sets may contain only source records that are intentionally
    # commented as non-validating under the strict WMDR2/OGC schema. The
    # regression value of this test is that every non-commented record must
    # validate, and every commented record that becomes valid must be removed
    # from KNOWN_NONVALIDATING_E2E_OUTPUTS.
    assert not unexpectedly_valid, "Remove now-valid record(s) from KNOWN_NONVALIDATING_E2E_OUTPUTS: " + ", ".join(unexpectedly_valid)
    assert not failures, "\n".join(failures[:20])
